language: bash

before_install:
  # To install bats and test our shell/bash functions
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats trash-cli realpath
  - sudo useradd prueba

# For bats functional tests

# command to run tests
script:
    - bats --tap tests/

notifications:
  email:
    on_success: never
