language: bash
sudo: false

  #       sources:
  # # To install bats and test our shell/bash functions
  # - ppa:duggan/bats 
addons:
  apt:
    packages:
        - bats
        - trash-cli
        - realpath

before_install:
  - useradd prueba

# For bats functional tests

# command to run tests
script:
    - bats --tap tests/

notifications:
  email:
    on_success: never
    on_failure: never
